#pragma once

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define PERMISSIVE_HOLD

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
#define UNICODE_CYCLE_PERSIST false

